version: '3.3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend
    container_name: backend
    restart: unless-stopped
    command: ["./wait-for.sh", "db:27017", "--", "npm", "run", "dev"]
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    environment:
      - MONGO_USERNAME=ruhan
      - MONGO_PASSWORD=webstore
      - MONGO_HOSTNAME=db
      - MONGO_PORT=27017
      - MONGO_DB=webstore
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network
  db:
      build:
        context: ./db
        dockerfile: Dockerfile
      container_name: db
      restart: unless-stopped
      ports:
      - "27017:27017"
      environment:
        - MONGO_INITDB_ROOT_USERNAME=ruhan
        - MONGO_INITDB_ROOT_PASSWORD=webstore
      volumes:     
        - dbdata:/data/db
      networks:
        - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata: