version: "3.3"

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: db
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ruhan
      - MONGO_INITDB_ROOT_PASSWORD=webstore
      - MONGO_INITDB_DATABASE=webstore
      - MONGO_DB_DEV=webstore_dev
      - MONGO_DB_TEST=webstore_test
    volumes:
      - dbdata:/data/db
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend
    container_name: backend
    restart: unless-stopped
    command: ["./wait-for.sh", "db:27017", "--", "npm", "run", "dev"]
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    environment:
      - MONGO_USERNAME=ruhan
      - MONGO_PASSWORD=webstore
      - MONGO_HOSTNAME=db
      - MONGO_PORT=27017
      - MONGO_DB=webstore
      - MONGO_DB_DEV=webstore_dev
      - MONGO_DB_TEST=webstore_test
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network

  frontend:
    image: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    stdin_open: true
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - API_URL=backend:8080
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
