const _ = require("lodash");
const validUsers = [
  {
    userType: "registered",
    userData: {
      firstName: "Demo user",
      lastName: "One",
      email: "demo.user@one.fi",
      password: "ZAQ!2wsx",
      userType: "registered",
      bankName: "Nordea",
      accountNo: "FI21 1234 5600 0007 80",
    },
  },
  {
    userType: "shopkeeper",
    userData: {
      firstName: "Demo user",
      lastName: "Two",
      email: "demo.user@two.fi",
      password: "ZAQ!2wsx",
      userType: "shopkeeper",
      bankName: "Nordea",
      accountNo: "FI21 1234 5600 0007 81",
    },
  },
];

const invalidUsers = [
  {
    name: "create admin again",
    user: {
      firstName: "invalid",
      lastName: "admin",
      email: "demo@admin.fi",
      password: "ZAQ!2wsx",
      userType: "admin",
      bankName: "Nordea",
      accountNo: "FI21 1234 5678 9012 34",
    },
    message: "User can not be admin",
  },
  {
    name: "duplicate email",
    user: {
      firstName: "invalid",
      lastName: "user",
      email: "demo.user@one.fi",
      password: "ZAQ!2wsx",
      userType: "registered",
      bankName: "Nordea",
      accountNo: "FI21 1234 5678 9012 34",
    },
    message: "User already registered",
  },
  {
    name: "duplicate account no",
    user: {
      firstName: "invalid",
      lastName: "user",
      email: "invalid.user@one.fi",
      password: "ZAQ!2wsx",
      userType: "registered",
      bankName: "Nordea",
      accountNo: "FI21 1234 5600 0007 80",
    },
    message: "Expected accountNo value to be unique",
  },
  {
    name: "first name lenght < 2",
    user: {
      firstName: "i",
      lastName: "user",
      email: "invalid.user@one.fi",
      password: "ZAQ!2wsx",
      userType: "registered",
      bankName: "Nordea",
      accountNo: "FI21 1234 5678 9012 34",
    },
    message: '"firstName" length must be at least 2 characters long',
  },
  {
    name: "first name lenght > 50",
    user: {
      firstName: _.repeat("*", 51),
      lastName: "user",
      email: "invalid.user@one.fi",
      password: "ZAQ!2wsx",
      userType: "registered",
      bankName: "Nordea",
      accountNo: "FI21 1234 5678 9012 34",
    },
    message:
      '"firstName" length must be less than or equal to 50 characters long',
  },
  {
    name: "last name lenght < 2",
    user: {
      firstName: "invalid",
      lastName: "u",
      email: "invalid.user@one.fi",
      password: "ZAQ!2wsx",
      userType: "registered",
      bankName: "Nordea",
      accountNo: "FI21 1234 5678 9012 34",
    },
    message: '"lastName" length must be at least 2 characters long',
  },
  {
    name: "last name lenght > 50",
    user: {
      firstName: "invalid",
      lastName: _.repeat("*", 51),
      email: "invalid.user@one.fi",
      password: "ZAQ!2wsx",
      userType: "registered",
      bankName: "Nordea",
      accountNo: "FI21 1234 5678 9012 34",
    },
    message:
      '"lastName" length must be less than or equal to 50 characters long',
  },
  {
    name: "invalid email address: one",
    user: {
      firstName: "invalid",
      lastName: "user",
      email: "invalid.user",
      password: "ZAQ!2wsx",
      userType: "registered",
      bankName: "Nordea",
      accountNo: "FI21 1234 5678 9012 34",
    },
    message: '"email" must be a valid email',
  },
  {
    name: "invalid email address: two",
    user: {
      firstName: "invalid",
      lastName: "user",
      email: "#@%^%#$@#$@#.com",
      password: "ZAQ!2wsx",
      userType: "registered",
      bankName: "Nordea",
      accountNo: "FI21 1234 5678 9012 34",
    },
    message: '"email" must be a valid email',
  },
  {
    name: "invalid email address: three",
    user: {
      firstName: "invalid",
      lastName: "user",
      email: "@example.com",
      password: "ZAQ!2wsx",
      userType: "registered",
      bankName: "Nordea",
      accountNo: "FI21 1234 5678 9012 34",
    },
    message: '"email" must be a valid email',
  },
  {
    name: "invalid email address: four",
    user: {
      firstName: "invalid",
      lastName: "user",
      email: "Joe Smith <email@example.com>",
      password: "ZAQ!2wsx",
      userType: "registered",
      bankName: "Nordea",
      accountNo: "FI21 1234 5678 9012 34",
    },
    message: '"email" must be a valid email',
  },
  {
    name: "invalid email address: five",
    user: {
      firstName: "invalid",
      lastName: "user",
      email: "email.example.com",
      password: "ZAQ!2wsx",
      userType: "registered",
      bankName: "Nordea",
      accountNo: "FI21 1234 5678 9012 34",
    },
    message: '"email" must be a valid email',
  },
  {
    name: "invalid email address: six",
    user: {
      firstName: "invalid",
      lastName: "user",
      email: "email@example@example.com",
      password: "ZAQ!2wsx",
      userType: "registered",
      bankName: "Nordea",
      accountNo: "FI21 1234 5678 9012 34",
    },
    message: '"email" must be a valid email',
  },
  {
    name: "invalid email address: seven",
    user: {
      firstName: "invalid",
      lastName: "user",
      email: ".email@example.com",
      password: "ZAQ!2wsx",
      userType: "registered",
      bankName: "Nordea",
      accountNo: "FI21 1234 5678 9012 34",
    },
    message: '"email" must be a valid email',
  },
  {
    name: "invalid email address: eight",
    user: {
      firstName: "invalid",
      lastName: "user",
      email: "email.@example.com",
      password: "ZAQ!2wsx",
      userType: "registered",
      bankName: "Nordea",
      accountNo: "FI21 1234 5678 9012 34",
    },
    message: '"email" must be a valid email',
  },
  {
    name: "invalid email address: nine",
    user: {
      firstName: "invalid",
      lastName: "user",
      email: "email..email@example.com",
      password: "ZAQ!2wsx",
      userType: "registered",
      bankName: "Nordea",
      accountNo: "FI21 1234 5678 9012 34",
    },
    message: '"email" must be a valid email',
  },
  {
    name: "invalid email address: eleven",
    user: {
      firstName: "invalid",
      lastName: "user",
      email: "email@example.com (Joe Smith)",
      password: "ZAQ!2wsx",
      userType: "registered",
      bankName: "Nordea",
      accountNo: "FI21 1234 5678 9012 34",
    },
    message: '"email" must be a valid email',
  },
  {
    name: "invalid email address: twelve",
    user: {
      firstName: "invalid",
      lastName: "user",
      email: "email@-example.com",
      password: "ZAQ!2wsx",
      userType: "registered",
      bankName: "Nordea",
      accountNo: "FI21 1234 5678 9012 34",
    },
    message: '"email" must be a valid email',
  },
  {
    name: "password lenght < 5",
    user: {
      firstName: "invalid",
      lastName: "user",
      email: "email@example.com",
      password: "ZAQ!",
      userType: "registered",
      bankName: "Nordea",
      accountNo: "FI21 1234 5678 9012 34",
    },
    message: '"password" length must be at least 5 characters long',
  },
  {
    name: "password lenght > 50",
    user: {
      firstName: "invalid",
      lastName: "user",
      email: "email@example.com",
      password: _.repeat("*", 51),
      userType: "registered",
      bankName: "Nordea",
      accountNo: "FI21 1234 5678 9012 34",
    },
    message:
      '"password" length must be less than or equal to 50 characters long',
  },
  {
    name: "invalid user type",
    user: {
      firstName: "invalid",
      lastName: "user",
      email: "email@example.com",
      password: "ZAQ!2wsx",
      userType: "invalid",
      bankName: "Nordea",
      accountNo: "FI21 1234 5678 9012 34",
    },
    message: '"userType" must be one of [admin, shopkeeper, registered]',
  },
  {
    name: "bank name length < 2",
    user: {
      firstName: "invalid",
      lastName: "user",
      email: "email@example.com",
      password: "ZAQ!2wsx",
      userType: "registered",
      bankName: "N",
      accountNo: "FI21 1234 5678 9012 34",
    },
    message: '"bankName" length must be at least 2 characters long',
  },
  {
    name: "bank name length > 50",
    user: {
      firstName: "invalid",
      lastName: "user",
      email: "email@example.com",
      password: "ZAQ!2wsx",
      userType: "registered",
      bankName: _.repeat("*", 51),
      accountNo: "FI21 1234 5678 9012 34",
    },
    message:
      '"bankName" length must be less than or equal to 50 characters long',
  },
  {
    name: "wrong accunt no format: one",
    user: {
      firstName: "invalid",
      lastName: "user",
      email: "email@example.com",
      password: "ZAQ!2wsx",
      userType: "registered",
      bankName: "Nordea",
      accountNo: "FI21 1234 5678 9012 3",
    },
    message:
      "Account no should match the pattern like `XX00 0000 0000 0000 00`",
  },
  {
    name: "wrong accunt no format: two",
    user: {
      firstName: "invalid",
      lastName: "user",
      email: "email@example.com",
      password: "ZAQ!2wsx",
      userType: "registered",
      bankName: "Nordea",
      accountNo: "FI21 1234 5678 9012 AB",
    },
    message:
      "Account no should match the pattern like `XX00 0000 0000 0000 00`",
  },
  {
    name: "wrong accunt no format: three",
    user: {
      firstName: "invalid",
      lastName: "user",
      email: "email@example.com",
      password: "ZAQ!2wsx",
      userType: "registered",
      bankName: "Nordea",
      accountNo: "0121 1234 5678 9012 34",
    },
    message:
      "Account no should match the pattern like `XX00 0000 0000 0000 00`",
  },
  {
    name: "without first name",
    user: {
      lastName: "user",
      email: "email@example.com",
      password: "ZAQ!2wsx",
      userType: "registered",
      bankName: "Nordea",
      accountNo: "FI21 1234 5678 9012 34",
    },
    message: '"firstName" is required',
  },
  {
    name: "without first name",
    user: {
      firstName: "invalid",
      email: "email@example.com",
      password: "ZAQ!2wsx",
      userType: "registered",
      bankName: "Nordea",
      accountNo: "FI21 1234 5678 9012 34",
    },
    message: '"lastName" is required',
  },
  {
    name: "without email",
    user: {
      firstName: "invalid",
      lastName: "user",
      password: "ZAQ!2wsx",
      userType: "registered",
      bankName: "Nordea",
      accountNo: "FI21 1234 5678 9012 34",
    },
    message: '"email" is required',
  },
  {
    name: "without password",
    user: {
      firstName: "invalid",
      lastName: "user",
      email: "email@example.com",
      userType: "registered",
      bankName: "Nordea",
      accountNo: "FI21 1234 5678 9012 34",
    },
    message: '"password" is required',
  },
  {
    name: "without userType",
    user: {
      firstName: "invalid",
      lastName: "user",
      email: "email@example.com",
      password: "ZAQ!2wsx",
      bankName: "Nordea",
      accountNo: "FI21 1234 5678 9012 34",
    },
    message: '"userType" is required',
  },
  {
    name: "without bankName",
    user: {
      firstName: "invalid",
      lastName: "user",
      email: "email@example.com",
      password: "ZAQ!2wsx",
      userType: "registered",
      accountNo: "FI21 1234 5678 9012 34",
    },
    message: '"bankName" is required',
  },
  {
    name: "without accountNo",
    user: {
      firstName: "invalid",
      lastName: "user",
      email: "email@example.com",
      password: "ZAQ!2wsx",
      userType: "registered",
      bankName: "Nordea",
    },
    message:
      "Account no should match the pattern like `XX00 0000 0000 0000 00`",
  },
];

module.exports = {
  validUsers,
  invalidUsers,
};
